name: video_downloader
description: "Flutter video downloader"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  
  chewie: ^1.13.0
  dio: ^5.9.0
  flutter:
    sdk: flutter
 
  flutter_riverpod: ^3.0.3
  http: ^1.6.0
  path_provider: ^2.1.5
  sqflite: ^2.4.2
  url_launcher: ^6.3.2
  youtube_explode_dart: ^3.0.5
  shared_preferences: ^2.2.2
  window_size: ^0.1.0
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^17.2.3
  firebase_remote_config: ^5.5.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  

flutter:
  uses-material-design: true
  assets: 
   - assets/.

     

